name: WhoWas
main: org.aaron1011.whowas.impl.bukkit.BukkitPlugin
version: 1.0.0
author: Aaron1011

commands:
  whoWas:
    description: View the name history for a player
    usage: /whoWas <playerName>
    permission: whowas.whowas